routes/web.php
                Route::get('/', 'CmsPageController@index')->name('index');
                Route::get('/create', 'CmsPageController@create')->name('create')->middleware('permission:create_pages');
                Route::post('/store', 'CmsPageController@store')->name('store')->middleware('permission:create_pages');
                Route::get('/{id}/edit', 'CmsPageController@edit')->name('edit')->middleware('permission:edit_pages');
                Route::post('/{id}/update', 'CmsPageController@update')->name('update')->middleware('permission:edit_pages');
                Route::post('/', 'CmsPageController@action')->name('action')->middleware('permission:delete_pages');
            }
        );

        Route::group(['prefix' => 'service-fees', 'as' => 'service-fees.'],
            function () {
                Route::get('/', 'ServiceFeeController@index')->name('index');
                Route::post('/', 'ServiceFeeController@action')->name('action');
            }
        );

        Route::group(['prefix' => 'transport-fees', 'as' => 'transport-fees.'],
            function () {
                Route::get('/', 'TransportFeeController@index')->name('index');
                Route::post('/', 'TransportFeeController@action')->name('action');
            }
        );

        Route::group(['prefix' => 'count-fees', 'as' => 'count-fees.'],
            function () {
                Route::get('/', 'CountFeeController@index')->name('index');
                Route::post('/', 'CountFeeController@action')->name('action');
            }
        );

        Route::group(['prefix' => 'wood-fees', 'as' => 'wood-fees.'],
            function () {
                Route::get('/', 'WoodFeeController@index')->name('index');
                Route::post('/', 'WoodFeeController@action')->name('action');
            }
        );

        Route::group(['prefix' => 'customer-level', 'as' => 'customer-level.'],
            function () {
                Route::get('/', 'CustomerLevelController@index')->name('index');
                Route::post('/', 'CustomerLevelController@action')->name('action');
            }
        );

        Route::group(['prefix' => 'transport-orders', 'as' => 'transport-orders.'],
            function () {
                Route::get('/{id}/details', 'TransportOrderController@show')->name('detail');
                Route::get('/', 'TransportOrderController@index')->name('index');
                Route::post('/', 'TransportOrderController@action')->name('action');
                Route::get('/link-qty', 'TransportOrderController@renderLinkQty')->name('renderLinkQty');
                Route::get('/{id}/export', 'TransportOrderController@export')->name('export');
            }
        );

        Route::group(['prefix' => 'transport-order-items', 'as' => 'transport-order-items.'],
            function () {
                Route::get('/link-qty', 'TransportOrderItemController@renderLinkQty')->name('renderLinkQty');
                Route::post('/', 'TransportOrderItemController@action')->name('action');
            }
        );

        Route::group(
            [
                'prefix' => 'reports', 'as' => 'reports.',
                'middleware' => 'permission:view_reports'
            ],
            function() {
                Route::get('/debt', 'ReportController@debt')->name('debt');
                Route::post('/debt/export', 'ReportController@debtExport')->name('debt.export');
                Route::get('/revenue', 'ReportController@revenue')->name('revenue');
                Route::get('/export-revenue', 'ReportController@exportRevenue')->name('exportRevenue');
                Route::get('/calculation-revenue', 'ReportController@calculateRevenue')->name('calculateRevenue');
                Route::get('/calculation-debt', 'ReportController@calculateDebt')->name('calculateDebt');
                Route::post('/payment-debt', 'ReportController@paymentDebt')->name('paymentDebt');
            }
        );

        Route::group(['prefix' => 'transactions', 'as' => 'transactions.'],
            function () {
                Route::post('/', 'TransactionController@action')->name('action');
            }
        );

        Route::group(['prefix' => 'ship-codes', 'as' => 'ship-codes.'],
            function () {
                Route::get('/', 'ShipCodeController@index')->name('index');
                Route::get('/create-ship-code', 'ShipCodeController@formCreate')->name('create');
                Route::post('/edit', 'ShipCodeController@edit')->name('edit');
                Route::post('/create-update', 'ShipCodeController@createOrUpdate')->name('createOrUpdate');
                Route::get('/filter-customers', 'ShipCodeController@getCustomersByStatus')->name('filter');
                Route::get('/search', 'ShipCodeController@search')->name('search');
                Route::post('/get-excel', 'ShipCodeController@getExcel')->name('get-excel');
                Route::get('/page', 'ShipCodeController@pageItem')->name('page');
                Route::post('/delete', 'ShipCodeController@delete')->name('delete');
                Route::post('/import', 'ShipCodeController@import')->name('import');
            }
        );
    });
});

/*
|--------------------------------------------------------------------------
| Frontend Routes
|--------------------------------------------------------------------------
|
*/
Route::get('/', 'HomeController@index')->name('home-page');

Route::group(['prefix' => config('auth.guard_customers.prefix'), 'namespace' => 'Customers', 'as' => 'customers.'], function () {
    Auth::routes();
    Route::get('/', 'CustomerController@showProfile')->name('showProfile');
    Route::get('/update-password', 'CustomerController@showFormUpdatePassword')->name('showFormUpdatePassword');
    Route::post('/update-password', 'CustomerController@updatePassword')->name('updatePassword');
    Route::get('/debt', 'CustomerController@debt')->name('debt');
    Route::post('/update/{customer_id}', 'CustomerController@update')->name('update');

    Route::group(['prefix' => 'delivery-address', 'as' => 'delivery-address.'], function () {
        Route::post('/new', 'CustomerController@createDeliveryAddress')->name('create');
        Route::post('/update', 'CustomerController@updateDeliveryAddress')->name('update');
        Route::get('/ajax-search/{id}', 'CustomerController@ajaxSearchAddress')->name('ajaxSearch');
        Route::post('/update-default/{id}', 'CustomerController@updateAddressDefault')->name('updateDefault');
    });

    Route::group(['prefix' => 'notifications', 'as' => 'notifications.'], function(){
        Route::get('/', 'NotificationController@index')->name('index');
        Route::get('/read/{id}', 'NotificationController@read')->name('read');
    });
});

Route::group(['prefix' => 'orders', 'as' => 'orders.', 'namespace' => 'Customers'], function () {
    Route::get('/export', 'OrderController@export')->name('export');
    Route::post('/temps', 'OrderTempController@store');
    Route::post('/update/transport/{id}', 'OrderController@updateTransport')->name('updateTransport');
    Route::get('/find/transport/{id}', 'OrderController@ajaxFindTransport')->name('ajaxFindTransport');
    Route::get('/temps', 'OrderTempController@show')->name('temps.show');
    Route::get('/transports', 'OrderController@indexTransportOrder')->name('indexTransportOrder');
    Route::get('/export-transports', 'OrderController@exportTransportOrder')->name('exportTransportOrder');
    Route::post('/transports/store', 'OrderController@storeTransportOrder')->name('storeTransportOrder');
    Route::get('/transports/{id}/detail', 'OrderController@showTransportOrderDetail')->name('showTransportOrderDetail');
    Route::get('/purchases', 'OrderController@indexPurchaseOrder')->name('purchases.index');
    Route::post('/purchases', 'OrderController@storePurchaseOrder')->name('purchases.store');
    Route::get('/purchases/{id}', 'OrderController@showPurchaseOrder')->name('purchases.show');
    Route::post('/send-order/{id}', 'OrderController@sendOrder')->name('send-order');
    Route::post('/cancel-order/{id}', 'OrderController@cancelOrder')->name('cancel-order');
    Route::get('/{id}/pay', 'OrderController@showDepositView')->name('show-deposit-view');
    Route::get('/{id}/link-qty', 'OrderController@renderLinkQty')->name('renderLinkQty');
    Route::delete('/{id}', 'OrderController@destroy')->name('delete');
});

Route::group(['prefix' => 'purchase-items', 'as' => 'purchase-items.', 'namespace' => 'Customers'], function () {
    Route::delete('/{id}', 'PurchaseOrderItemController@destroy')->name('delete');
});

Route::group(['prefix' => 'feedback', 'as' => 'feedback.', 'namespace' => 'Admin'],
    function () {
        Route::post('/sent', 'FeedbackController@send')->name('send');
    }
);

Route::group(['prefix' => 'blog', 'as' => 'blog.', 'namespace' => 'Customers'],
    function () {
        Route::get('/', 'BlogController@index')->name('index');
        Route::get('/{slug}', 'BlogController@show')->name('show');
    }
);
Route::group(['prefix' => 'ship-codes', 'as' => 'ship_codes.', 'namespace' => 'Customers'],
    function () {
        Route::get('/', 'ShipCodeController@index')->name('index');
        Route::get('/search', 'ShipCodeController@search')->name('search');
    }
);

Route::get('/search-product', 'Customers\CustomerController@searchProduct')->name('searchProduct');

Route::get('/api/transactions', 'Api\TransactionController@byCustomer')->name('api.transactions.byCustomer');
Route::get('/api/orders', 'Api\OrderController@byCustomer')->name('api.orders.byCustomer');
Route::get('/api/customers/{id}/orders', 'Api\CustomerController@findOrderByCustomer')->name('api.users.findOrderByCustomer');
Route::get('/api/customers/{id}/transactions', 'Api\CustomerController@findTransactionByCustomer')->name('api.users.findTransactionByCustomer');

app/Models/Notification.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Notification extends Model
{
}

app/Http/Controllers/Customers/NotificationController.php
<?php

namespace App\Http\Controllers\Customers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class NotificationController extends Controller
{
    protected $notificationRepository;

    /**
     * NotificationController constructor.
     */
    public function  __construct()
    {
        $this->notificationRepository = app('NotificationRepositoryInterface');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $notifications =  $this->notificationRepository->getFilterCustomerNotification();
        return view('frontend.notifications.index', compact('notifications'));
    }

    /**
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function read($id)
    {
        $this->notificationRepository->markAsRead($id);
        return redirect()->to(request()->redirect);
    }
}

resources/views/frontend/notifications/index.blade.php
@extends('layouts.frontend')
@section('style')
    {{ Html::style(asset('vendor/bootstrap-datepicker/bootstrap-datepicker.css')) }}
@stop
@section('page')
    <div class="container">
        <h2 class="text-uppercase">@lang('page-name.title_order_index')</h2>
        <hr>
        @include('components.notification')
        <div class="row">
            <div class="col-md-3">
                @include('components.site_bar')
            </div>
            <div class="col-md-9">
                <form action="{{ route('customers.notifications.index') }}" method="GET" class="pt-4">
                    <div class="row">
                        <div class="col-md-3">
                            <div class="input-group input-group-sm">
                                <select name="status" class="form-control">
                                    <option {{ request()->status === '-1' ? 'selected' : '' }} value="-1">@lang('form.title_all')</option>
                                    <option {{ request()->status === '0' ? 'selected' : '' }} value="0">@lang('form.title_unread')</option>
                                    <option {{ request()->status === '1' ? 'selected' : '' }} value="1">@lang('form.title_read')</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="input-group input-group-sm">
                                <input name="start_date" value="{{ request('start_date') }}" type="text" class="form-control js-start-date search-order" placeholder="@lang('form.placeholder_start_date')">
                                <span class="input-group-addon"><i class="fa fa-calendar order-icon-search"></i></span>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="input-group input-group-sm">
                                <input name="end_date" value="{{ request('end_date') }}" type="text" class="form-control js-end-date search-order" placeholder="@lang('form.placeholder_end_date')">
                                <span class="input-group-addon"><i class="fa fa-calendar order-icon-search"></i></span>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <button class="btn btn-sm btn-danger pull-right ml-2"><i class="fa fa-filter"></i> @lang('form.filter')</button>
                        </div>
                    </div>
                    <br>
                </form>
                <div class="row pt-4">
                    <div class="col-md-12">
                        <div class="order-list">
                            <div class="table">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>@lang('table.created_at')</th>
                                        <th>@lang('table.message')</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @if($notifications->count() > 0)
                                        @foreach($notifications as $notification)
                                            <tr class="{{ $notification->read_at == null ? 'font-weight-bold' : '' }}">
                                                <td>{{ $notification->created_at->format('d/m/Y h:i') }}</td>
                                                <td>
                                                    Đơn hàng <a href="{{ route('customers.notifications.read', ['id' => $notification->id, 'redirect' => $notification->data['link']]) }}">{{ $notification->data['order_number'] }}</a> đã được báo giá
                                                </td>
                                            </tr>
                                        @endforeach
                                    @endif
                                    </tbody>
                                </table>
                                {{ $notifications->appends(request()->query())->links('vendor.pagination.bootstrap-4') }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('script')
    @parent
    <script src="{{ asset('vendor/bootstrap-datepicker/bootstrap-datepicker.js') }}"></script>
    <script>
        $(function() {
            var app = new Application();
            app.initDatePickerValidateEndDate();
        });
    </script>
@stop