routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function () {
    Auth::routes();
    Route::middleware('auth')->group(function () {
        Route::get('/', 'OrderController@indexPurchaseOrder')->name('index');
        Route::group(
            [
                'middleware' => ['permission:create_users|edit_users|delete_users']
            ], function () {
            Route::get('users', 'UserController@index')->name('users.index');
            Route::post('users', 'UserController@action')->name('users.action');
        });

        Route::group(
            [
                'prefix' => 'exchange-rate', 'as' => 'exchange-rate.',
                'middleware' => ['permission:create_exchange_rates|edit_exchange_rates|delete_exchange_rates']
            ],
            function () {
                Route::get('/', 'ExchangeRateController@index')->name('index');
                Route::post('/', 'ExchangeRateController@action')->name('action');
            }
        );

        Route::group(['prefix' => 'orders', 'as' => 'orders.'],
            function () {
                Route::get('/purchases/{id}/details', 'OrderController@showPurchaseOrderDetail')->name('purchases.detail');
                Route::get('/show-order/{customer_id}', 'OrderController@showByCustomerId')->name('showByCustomerId');
                Route::get('/purchases', 'OrderController@indexPurchaseOrder')->name('purchases.index');
                Route::post('/purchases', 'OrderController@actionPurchaseOrder')->name('purchases.action');
                Route::get('/purchases/{id}/export', 'OrderController@exportPurchaseOrder')->name('purchases.export');
                Route::delete('/purchases/{id}', 'OrderController@destroy')->name('delete');
            }
        );

        Route::group(['prefix' => 'purchases-order-items', 'as' => 'order-items.'],
            function () {
                Route::post('/', 'PurchaseOrderItemController@action')->name('action');
            }
        );

        Route::group(
            [
                'prefix' => 'customers', 'as' => 'customers.',
                'middleware' => 'permission:view_customer_info|create_customers'
            ],
            function () {
                Route::get('/', 'CustomerController@index')->name('index');
                Route::post('/', 'CustomerController@action')->name('action');
                Route::get('/{id}/transactions', 'CustomerController@showTransaction')->name('show-transactions');
            }
        );

        Route::group(
            [
                'prefix' => 'feedback', 'as' => 'feedback.',
                'middleware' => ['permission:view_feedback']
            ],
            function () {
                Route::get('/', 'FeedbackController@index')->name('index');
            }
        );

        Route::group(
            [
                'prefix' => 'slides', 'as' => 'slides.',
                'middleware' => ['permission:create_slides|edit_slides|delete_slides']
            ],
            function () {
                Route::get('/{group}', 'SlideController@index')->name('index');
                Route::post('/', 'SlideController@action')->name('action');
            }
        );
        Route::group(['prefix' => 'permissions', 'as' => 'permissions.'],
            function () {
                Route::get('/', 'PermissionController@index')->name('index');
                Route::post('/', 'PermissionController@action')->name('action');
            }
        );
        Route::group(
            [
                'prefix' => 'roles', 'as' => 'roles.',
                'middleware' => ['permission:create_roles|edit_roles|delete_roles']
            ],
            function () {
                Route::get('/', 'RoleController@index')->name('index');
                Route::post('/', 'RoleController@action')->name('action')->middleware('permission:delete_roles');
                Route::get('/{id}/edit', 'RoleController@edit')->name('edit')->middleware('permission:edit_roles');
                Route::post('/store', 'RoleController@store')->name('store')->middleware('permission:create_roles');
                Route::post('/{id}', 'RoleController@update')->name('update')->middleware('permission:edit_roles');
                Route::get('/create', 'RoleController@create')->name('create')->middleware('permission:create_roles');
            }
        );

        Route::group(['prefix' => 'blogs', 'as' => 'blogs.'], function () {
            Route::get('/', 'BlogController@index')->name('index')->middleware('permission:create_blogs|edit_blogs|delete_blogs');
            Route::get('/create', 'BlogController@create')->name('create')->middleware('permission:create_blogs');
            Route::post('/store', 'BlogController@store')->name('store')->middleware('permission:create_blogs');
            Route::get('/{id}/edit', 'BlogController@edit')->name('edit')->middleware('permission:edit_blogs');
            Route::post('/{id}/update', 'BlogController@update')->name('update')->middleware('permission:edit_blogs');
            Route::post('/', 'BlogController@action')->name('action');
        });

        Route::group(
            [
                'prefix' => 'website-configs', 'as' => 'website-configs.',
                'middleware' => ['permission:edit_website_configs']
            ],
            function () {
                Route::get('/', 'WebsiteConfigController@index')->name('index');
                Route::post('/', 'WebsiteConfigController@action')->name('action');
            }
        );

        Route::group(
            [
                'prefix' => 'cms-pages', 'as' => 'cms-pages.',
                'middleware' => ['permission:create_pages|edit_pages|delete_pages']
            ],
            function () {
                Route::get('/', 'CmsPageController@index')->name('index');
                Route::get('/create', 'CmsPageController@create')->name('create')->middleware('permission:create_pages');
                Route::post('/store', 'CmsPageController@store')->name('store')->middleware('permission:create_pages');
                Route::get('/{id}/edit', 'CmsPageController@edit')->name('edit')->middleware('permission:edit_pages');
                Route::post('/{id}/update', 'CmsPageController@update')->name('update')->middleware('permission:edit_pages');
                Route::post('/', 'CmsPageController@action')->name('action')->middleware('permission:delete_pages');
            }
        );

        Route::group(['prefix' => 'service-fees', 'as' => 'service-fees.'],
            function () {
                Route::get('/', 'ServiceFeeController@index')->name('index');
                Route::post('/', 'ServiceFeeController@action')->name('action');
            }
        );

        Route::group(['prefix' => 'transport-fees', 'as' => 'transport-fees.'],
            function () {
                Route::get('/', 'TransportFeeController@index')->name('index');
                Route::post('/', 'TransportFeeController@action')->name('action');
            }
        );

        Route::group(['prefix' => 'count-fees', 'as' => 'count-fees.'],
            function () {
                Route::get('/', 'CountFeeController@index')->name('index');
                Route::post('/', 'CountFeeController@action')->name('action');
            }
        );

        Route::group(['prefix' => 'wood-fees', 'as' => 'wood-fees.'],
            function () {
                Route::get('/', 'WoodFeeController@index')->name('index');
                Route::post('/', 'WoodFeeController@action')->name('action');
            }
        );

        Route::group(['prefix' => 'customer-level', 'as' => 'customer-level.'],
            function () {
                Route::get('/', 'CustomerLevelController@index')->name('index');
                Route::post('/', 'CustomerLevelController@action')->name('action');
            }
        );

        Route::group(['prefix' => 'transport-orders', 'as' => 'transport-orders.'],
            function () {
                Route::get('/{id}/details', 'TransportOrderController@show')->name('detail');
                Route::get('/', 'TransportOrderController@index')->name('index');
                Route::post('/', 'TransportOrderController@action')->name('action');
                Route::get('/link-qty', 'TransportOrderController@renderLinkQty')->name('renderLinkQty');
                Route::get('/{id}/export', 'TransportOrderController@export')->name('export');
            }
        );

        Route::group(['prefix' => 'transport-order-items', 'as' => 'transport-order-items.'],
            function () {
                Route::get('/link-qty', 'TransportOrderItemController@renderLinkQty')->name('renderLinkQty');
                Route::post('/', 'TransportOrderItemController@action')->name('action');
            }
        );

        Route::group(
            [
                'prefix' => 'reports', 'as' => 'reports.',
                'middleware' => 'permission:view_reports'
            ],
            function() {
                Route::get('/debt', 'ReportController@debt')->name('debt');
                Route::post('/debt/export', 'ReportController@debtExport')->name('debt.export');
                Route::get('/revenue', 'ReportController@revenue')->name('revenue');
                Route::get('/export-revenue', 'ReportController@exportRevenue')->name('exportRevenue');
                Route::get('/calculation-revenue', 'ReportController@calculateRevenue')->name('calculateRevenue');

app/Http/Controllers/Admin/OrderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\DataTables\PurchaseOrderDatatable;
use App\DataTables\PurchaseOrderDataTablesEditor;
use App\DataTables\OrderOfCustomerDataTable;
use App\Exports\PurchaseOrderExport;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Yajra\DataTables\DataTables;

/**
 * Class OrderController
 *
 * @package App\Http\Controllers\Admin
 */
class OrderController extends Controller
{
    protected $customerRepository;
    protected $orderRepository;

    /**
     * OrderController constructor.
     */
    public function __construct()
    {
        $this->customerRepository = app('CustomerRepositoryInterface');
        $this->orderRepository = app('OrderRepositoryInterface');
    }

    /**
     * @param PurchaseOrderDatatable $dataTable
     * @return mixed
     */
    public function indexPurchaseOrder(PurchaseOrderDatatable $dataTable)
    {
        return $dataTable->render('admins.orders.index');
    }

    /**
     * Action order
     *
     * @param PurchaseOrderDataTablesEditor $editor
     * @return \Illuminate\Http\JsonResponse|mixed
     * @throws \Yajra\DataTables\DataTablesEditorException
     */
    public function actionPurchaseOrder(PurchaseOrderDataTablesEditor $editor)
    {
        return $editor->process(request());
    }


    /**
     * @param $id
     * @return mixed
     * @throws \Exception
     */
    public function showPurchaseOrderDetail($id)
    {
        $orderItems = $this->orderRepository->getOneById($id)->purchaseOrderItems->load('orderGroup', 'order');
        return Datatables::of($orderItems)
                            ->addColumn('shop_name', function ($item) {
                                return optional($item->orderGroup)->shop_name;
                            })
                            ->skipPaging()->make(true);
    }

    /**
     * Show orders of customer
     *
     * @param $customerId
     * @param OrderOfCustomerDataTable $dataTable
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function showByCustomerId($customerId, OrderOfCustomerDataTable $dataTable)
    {
        $customer = $this->customerRepository->getOneById($customerId);

        return $dataTable->with(['id' => $customerId])->render('admins.orders.orders_of_customer', compact('customer'));
    }

    /**
     * @param                     $id
     * @param PurchaseOrderExport $order
     * @return mixed
     */
    public function exportPurchaseOrder($id, PurchaseOrderExport $order)
    {
        $orderNumber = $this->orderRepository->getOneById($id)->order_number;
        $export = app('ExportInterface');
        return $export->export($order, 'Đơn hàng mua hộ ' . $orderNumber .'.xlsx');
    }

    /**
     * Delete transport order
     *
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        try {
            $this->orderRepository->delete($id);
            Session::flash('notification', ['status' => 'success', 'message' => trans('message.delete_transport_order_success')]);
            return back();
        } catch (Exception $exception) {
            Log::error(
                [
                    'method'  => __METHOD__,
                    'line'    => __LINE__,
                    'message' => 'Lỗi khi xóa đơn vận chuyển',
                    'context' => [
                        'id'          => $id,
                        'error_message' => $exception->getMessage()
                    ],
                ]
            );
            Session::flash('notification', ['status' => 'error', 'message' => trans('message.delete_transport_order_error')]);
            return back();
        }
    }
}

app/Http/Controllers/Api/OrderController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class OrderController extends Controller
{
    protected $orderRepository;

    /**
     * OrderController constructor.
     */
    public function __construct()
    {
        $this->orderRepository = app('OrderRepositoryInterface');
    }

    public function byCustomer()
    {
        $orders = $this->orderRepository->findPriceQuotation();
        return response()->json($orders);
    }
}

resources/views/frontend/orders/create.blade.php
@extends('layouts.frontend')
@section('page')
    <div class="container">
        <h2 class="text-uppercase">@lang('page-name.title_deposite')</h2>
        <hr>
        @include('components.notification')
        <div class="row">
            <div class="col-md-12">
                <h3 class="text-uppercase">@lang('form.final_total_price') : {{ $order->final_total_price }}</h3>
            </div>

        </div>
        <div class="row">
            <div class="col-md-4">
                <p>Thanh toán tiền mặt</p>
            </div>
            <div class="col-md-8">
                <ul>
                    <li>Công ty BSE Tầng 8, P.805, Tòa nhà Toyota Thanh Xuân, 315 Trường Chinh, Thanh Xuân, Hà Nội.</li>
                    <li>Công ty BSE Tầng 8, P.805, Tòa nhà Toyota Thanh Xuân, 315 Trường Chinh, Thanh Xuân, Hà Nội.</li>
                    <li>Công ty BSE Tầng 8, P.805, Tòa nhà Toyota Thanh Xuân, 315 Trường Chinh, Thanh Xuân, Hà Nội.</li>
                </ul>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <p>Thanh toán chuyển khoản</p>
            </div>
            <div class="col-md-8">
                <ul>
                    <li>Công ty BSE Tầng 8, P.805, Tòa nhà Toyota Thanh Xuân, 315 Trường Chinh, Thanh Xuân, Hà Nội.</li>
                    <li>Công ty BSE Tầng 8, P.805, Tòa nhà Toyota Thanh Xuân, 315 Trường Chinh, Thanh Xuân, Hà Nội.</li>
                    <li>Công ty BSE Tầng 8, P.805, Tòa nhà Toyota Thanh Xuân, 315 Trường Chinh, Thanh Xuân, Hà Nội.</li>
                </ul>
            </div>
        </div>
    </div>
@stop

resources/views/frontend/orders/deposit.blade.php
@extends('layouts.frontend')
@section('page')
    <div class="container">
        <h2 class="text-uppercase">@lang('page-name.title_deposite')</h2>
        <hr>
        @include('components.notification')
        <div class="row">
            <div class="col-md-12">
                <h3 class="text-uppercase">@lang('form.final_total_price') : {{ number_format($order->final_total_price) }}  @lang('form.title_vnd')</h3>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <p><strong>@lang('form.title_payment_cash_in_address')</strong></p>
                    </div>
                    <div class="card-body">
                        <div class="col-lg-10 offset-lg-1">
                            {!! $paymentCashInfo->content !!}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-12 payment-transfer-detail">
                <div class="card">
                    <div class="card-header">
                        <p><strong>@lang('form.title_payment_transfer')</strong></p>
                    </div>
                    <div class="card-body">
                        <div class="col-lg-10 offset-lg-1">
                            {!! $paymentTransferInfo->content !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/frontend/orders/index.blade.php
@extends('layouts.frontend')
@section('style')
    {{ Html::style(asset('vendor/bootstrap-datepicker/bootstrap-datepicker.css')) }}
@stop
@section('page')
    <div class="container">
        <h2 class="text-uppercase">@lang('page-name.title_order_index')</h2>
        <hr>
        @include('components.notification')
        <div class="row">
            <div class="col-md-3">
                @include('components.site_bar')
            </div>
            <div class="col-md-9">
                <ul class="list-inline">
                    <li class="list-inline-item {{ request()->status ? '': 'filter-active' }}"><a href="{{ route('orders.purchases.index') }}">@lang('form.title_all')( {{ $allOrderCount }} )</a></li>
                    <li class="list-inline-item {{ request()->status == STATUS_UNSENT ? 'filter-active' : ''}}"><a href="{{ route('orders.purchases.index') }}?status={{ STATUS_UNSENT }}">@lang('form.title_unsent')( {{ $unsentOrderCount }} )</a></li>
                    <li class="list-inline-item {{ request()->status == STATUS_PROCESSING ? 'filter-active' : ''}}"><a href="{{ route('orders.purchases.index') }}?status={{ STATUS_PROCESSING }}">@lang('form.title_processing')( {{ $processingOrderCount }})</a></li>
                    <li class="list-inline-item {{ request()->status == STATUS_PRICE_QUOTATION ? 'filter-active' : ''}}"><a href="{{ route('orders.purchases.index') }}?status={{ STATUS_PRICE_QUOTATION }}">@lang('form.title_price_quotation')( {{ $priceQuotationOrderCount }} )</a></li>
                    <li class="list-inline-item {{ request()->status == STATUS_ORDERED ? 'filter-active' : ''}}"><a href="{{ route('orders.purchases.index') }}?status={{ STATUS_ORDERED }}">@lang('form.title_ordered')( {{ $orderedOrderCount }} )</a></li>
                    <li class="list-inline-item {{ request()->status == STATUS_IN_WAREHOUSE ? 'filter-active' : ''}}"><a href="{{ route('orders.purchases.index') }}?status={{ STATUS_IN_WAREHOUSE }}">@lang('form.title_in_warehouse')( {{ $inWareHouseOrderCount }} )</a></li>
                    <li class="list-inline-item {{ request()->status == STATUS_SUCCESS ? 'filter-active' : ''}}"><a href="{{ route('orders.purchases.index') }}?status={{ STATUS_SUCCESS }}">@lang('form.title_success')( {{ $orderSuccessCount }} )</a></li>
                    <li class="list-inline-item {{ request()->status == STATUS_CANCEL ? 'filter-active' : ''}}"><a href="{{ route('orders.purchases.index') }}?status={{ STATUS_CANCEL }}">@lang('form.title_cancel')( {{ $orderCancelCount }} )</a></li>
                </ul>
                <form action="{{ route('orders.purchases.index') }}" method="GET" class="pt-4">
                    <div class="row">
                        <div class="col-md-3">
                            <div class="input-group input-group-sm">
                                <input name="order_number" value="{{ request('order_number') }}" type="text" class="form-control search-order" placeholder="@lang('form.placeholder_order_code')" autofocus>
                                <span class="input-group-addon"><i class="fa fa-search"></i></span>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="input-group input-group-sm">
                                <input name="transport_code" value="{{ request('transport_code') }}" type="text" class="form-control search-order" placeholder="@lang('form.placeholder_transport_code')">
                                <span class="input-group-addon"><i class="fa fa-search"></i></span>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="input-group input-group-sm">
                                <input name="start_date" value="{{ request('start_date') }}" type="text" class="form-control js-start-date search-order" placeholder="@lang('form.placeholder_start_date')">
                                <span class="input-group-addon"><i class="fa fa-calendar order-icon-search"></i></span>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="input-group input-group-sm">
                                <input name="end_date" value="{{ request('end_date') }}" type="text" class="form-control js-end-date search-order" placeholder="@lang('form.placeholder_end_date')">
                                <span class="input-group-addon"><i class="fa fa-calendar order-icon-search"></i></span>
                            </div>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="input-group input-group-sm">
                                <input name="product_link" value="{{ request('product_link') }}" type="text" class="form-control search-order" placeholder="@lang('form.placeholder_product_link')">
                                <span class="input-group-addon"><i class="fa fa-search"></i></span>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="input-group input-group-sm">
                                <input name="product_name" value="{{ request('product_name') }}" type="text" class="form-control search-order" placeholder="@lang('form.placeholder_product_name')">
                                <span class="input-group-addon"><i class="fa fa-search"></i></span>
                            </div>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md-12">
                            <button class="btn btn-sm btn-danger pull-right ml-2"><i class="fa fa-filter"></i> @lang('form.filter')</button>
                            <a href="{{ route('orders.export', request()->query()) }}" class="btn btn-sm btn-info pull-right"><i class="fa fa-download"></i> @lang('form.export_excel')</a>
                        </div>
                    </div>
                </form>

            </div>
        </div>
        <div class="row pt-4 purchase-order-show">
                @if($orders->count() > 0)
                    <div class="col-md-12">
                        <div class="order-list">
                            <div class="table table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>@lang('table.order_number')</th>
                                        <th>@lang('table.product_image')</th>
                                        <th>@lang('form.final_total_price')</th>
                                        <th>@lang('table.order_created_at')</th>
                                        <th>@lang('table.status')</th>
                                        <th>@lang('table.admin_note')</th>
                                        <th>@lang('table.action')</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($orders as $order)
                                        @php $item = $order->purchaseOrderItems->first(); @endphp
                                        <tr>
                                            <td>{{ config('data.prefix_order_number') . $order->order_number }}</td>
                                            <td class="td-image">
                                                <img src="{{ optional($item)->product_image }}" alt="" srcset="" width="70px" height="70px" class="pull-left">
                                                <span class="product-name">
                                                    {{ optional($item)->product_name }}
                                                </span>
                                                <br>
                                                <a class="product-link" href="{{ optional($item)->product_link }}">{{ optional($item)->product_link }}</a>
                                            </td>
                                            <td>
                                                {{ number_format($order->final_total_price) }}
                                            </td>
                                            <td>{{ $order->created_at->format('d/m/Y') }}</td>
                                            <td>{{ config('data.order_status')[$order->status] }}</td>
                                            <td>{{ $order->admin_note }}</td>
                                            <td>
                                                <a href="{{ route('orders.purchases.show', $order->id) }}" class="btn btn-primary btn-sm detail-button"> @lang('form.view_order_details')</a>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="mt-4">
                        {{ $orders->appends(request()->query())->links('vendor.pagination.bootstrap-4') }}
                    </div>
                @else
                    <div class="col-lg-9 offset-lg-3">
                        <h3 class="text-center">Không tìm thấy đơn hàng nào</h3>
                    </div>
                @endif
            </div>
    </div>
@stop

@section('script')
    @parent
    <script src="{{ asset('vendor/bootstrap-datepicker/bootstrap-datepicker.js') }}"></script>
    <script>
        $(function() {
            var app = new Application();
            app.initDatePickerValidateEndDate();
        });
    </script>
@stop